from django.urls import path

from .api import (
    analytics_overview,
    analytics_series,
    budget_detail,
    budgets,
    budgets_summary,
    categories,
    category_detail,
    forecast_expenses,
    health,
    insights,
    me,
    repeat_transaction,
    template_detail,
    templates,
    use_template,
    miniapp_auth,
    quick_add_create,
    quick_add_preview,
    summary,
    transaction_detail,
    transactions,
)

urlpatterns = [
    path("health/", health),
    path("miniapp/auth/", miniapp_auth),
    path("me/", me),
    path("categories/", categories),
    path("categories/<int:category_id>/", category_detail),
    path("templates/", templates),
    path("templates/<int:template_id>/", template_detail),
    path("templates/<int:template_id>/use/", use_template),
    path("transactions/", transactions),
    path("transactions/quick-add/preview/", quick_add_preview),
    path("transactions/quick-add/create/", quick_add_create),
    path("transactions/<int:tx_id>/", transaction_detail),
    path("transactions/<int:tx_id>/repeat/", repeat_transaction),
    path("summary/", summary),
    path("analytics/overview/", analytics_overview),
    path("analytics/series/", analytics_series),
    path("forecast/", forecast_expenses),
    path("insights/", insights),
    path("budgets/", budgets),
    path("budgets/<int:budget_id>/", budget_detail),
    path("budgets/summary/", budgets_summary),
]
